<section class="content-header">
    <h1>
        <?php echo $empresa_nome; ?>
        <small>Pagina empresa</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Empresa</li>
    </ol>
</section>

<section class="content">

    <div class="row">

        <div class="box">

            <div class="box-header">
                <i class="fa fa-archive"></i>

                <h3 class="box-title"><?php echo $empresa_nome; ?></h3>

            </div>
            <div class="box-body">
                <?php echo $empresa_texto; ?>
            </div>
            <?php if (isset($_SESSION['logado'])) { ?>
                <div class="col-xs-12">
                    <form action="/empresa/index" method="post">
                        <input type="hidden" name="id" value="<?php echo $empresa_id; ?>">
                        <textarea id="editor1" name="texto" rows="10" cols="80">
                            <?php echo $empresa_texto; ?>
                        </textarea>

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                            <a href="/produto" class="btn btn-primary">Voltar</a>
                        </div>
                    </form>
                </div>
            <?php } ?>
        </div>

    </div>
</section>