<div class="form-box" id="login-box">
    <div class="header">Gerenciamento</div>
    <?php if (isset($auth_status)) { ?>
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <span><?php echo $auth_status; ?></span>
        </div>
    <?php } ?>
    <form class="form" action="/auth/logar" method="post">
        <div class="body bg-gray">
            <div class="form-group">
                <input type="text" name="login" class="form-control" placeholder="Login"/>
            </div>
            <div class="form-group">
                <input type="password" name="loginPassword" class="form-control" placeholder="Senha"/>
            </div>
            <!--<div class="form-group">
                <input type="checkbox" name="remember_me"/> Manter conectado
            </div>-->
        </div>

        <div class="footer">
            <button type="submit" class="btn bg-olive btn-block">Logar</button>

            <!--<p><a href="#">Esqueci minha senha</a></p>

            <a href="register.html" class="text-center">Registrar uma nova associação</a>-->
        </div>
    </form>
    <!--
    <div class="margin text-center">
        <span>Sign in using social networks</span>
        <br/>
        <button class="btn bg-light-blue btn-circle"><i class="fa fa-facebook"></i></button>
        <button class="btn bg-aqua btn-circle"><i class="fa fa-twitter"></i></button>
        <button class="btn bg-red btn-circle"><i class="fa fa-google-plus"></i></button>

    </div>
    -->
</div>