<section class="content-header">
    <h1>
        Serviços
        <small>Pagina empresa</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="."><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Serviços</li>
    </ol>
</section>

<section class="content">

    <div class="row">

        <div class="box">

            <div class="box-header">
                <i class="fa fa-archive"></i>

                <h3 class="box-title">Pagina em desenvolvimento</h3>

            </div>
            <div class="box-body">

            </div>
        </div>

    </div>
</section>