<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Produto
        <small>cadastrar</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/produto">Produto</a></li>
        <li class="active">Cadastrar</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-8">

            <!-- /.box-header -->
            <div class="box-body table-responsive">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header">
                        <i class="fa fa-user"></i>

                        <h3 class="box-title">Cadastrar novo produto</h3>
                        <?php echo $produto_result; ?>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <!-- form start -->
                        <form class="form" action="add" method="post">

                            <div class="form-group">
                                <label for="nome">Nome</label>
                                <input type="text" class="form-control" name="nome" placeholder="Nome">
                            </div>
                            <div class="form-group">
                                <label for="valor">Valor</label>
                                <input type="text" class="form-control" id="valor" name="valor" placeholder="Valor">
                            </div>

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Salvar</button>
                                <a href="/produto" class="btn btn-primary">Voltar</a>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.box-body -->

        </div>
    </div>

</section><!-- /.content -->

