<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Usuários
        <small>alterar</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/user">Usuários</a></li>
        <li class="active">Alterar</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-8">

            <!-- /.box-header -->
            <div class="box-body table-responsive">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header">
                        <i class="fa fa-user"></i>

                        <h3 class="box-title">Alterar usuário</h3>
                        <?php echo $user_result; ?>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <!-- form start -->
                        <form class="form" action="/user/alt" method="post">
                            <input type="hidden" name="id" value="<?php echo $user_id; ?>">

                            <div class="form-group">
                                <label for="nome">Nome</label>
                                <input type="text" class="form-control" name="nome" value="<?php echo $user_nome; ?>"
                                       placeholder="Nome">
                            </div>
                            <div class="form-group">
                                <label for="cpf">CPF</label>
                                <input type="text" class="form-control" id="cpf" name="cpf"
                                       value="<?php echo $user_cpf; ?>" placeholder="CPF">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" name="email"
                                       value="<?php echo $user_email; ?>" placeholder="Email">
                            </div>
                            <!-- select -->
                            <div class="form-group">
                                <label>Tipo de usuário</label>
                                <?php
                                $select0 = ($user_status == 0 ? "selected" : null);
                                $select1 = ($user_status == 1 ? "selected" : null);
                                $select2 = ($user_status == 2 ? "selected" : null);
                                ?>
                                <select class="form-control" name="status">
                                    <option value="0" <?php echo $select0; ?>>Selecione</option>
                                    <option value="1" <?php echo $select1; ?>>Administrador</option>
                                    <option value="2" <?php echo $select2; ?>>Usuário</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="password">Senha</label>
                                <input type="password" class="form-control" id="password" name="password"
                                       placeholder="Senha">
                            </div>

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Alterar</button>
                                <a href="/user" class="btn btn-primary">Voltar</a>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.box-body -->

        </div>
    </div>

</section><!-- /.content -->

