<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Lista de Usuários
        <small>listagem</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="home"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="produto">Usuários</a></li>
        <li class="active">Lista de usuários</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Usuários</h3>
                    <?php echo $user_result; ?>
                </div>
                <div class="box-header">
                    <a class="btn btn-default" href="/user/add">Cadastrar usuário</a>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive">
                    <table id="grid1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Status</th>
                            <th>Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php

                        foreach ($user_listar as $key => $values) {
                            $status = ($values['status'] == 0 ? "<span class=\"label label-danger\">Desativado</span>" :
                                ($values['status'] == 1 ? "<span class=\"label label-success\">Administrador</span>" :
                                    ($values['status'] == 2 ? "<span class=\"label label-info\">Usuário</span>" : null)));
                            echo "<tr>" .
                                "<td>{$values['id']}</td>" .
                                "<td>{$values['nome']}</td>" .
                                "<td>{$status}</td>" .
                                "<td>" .
                                "<a href=\"/user/alt/{$values['id']}\" class=\"label label-default\">Alterar</a> " .
                                "<a href=\"/user/index/{$values['id']}\" class=\"label label-default\">Deletar</a>" .
                                "</td>" .
                                "</tr>";
                        }

                        ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Status</th>
                            <th>Ação</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

</section><!-- /.content -->

